# Generated by Django 4.1.3 on 2022-11-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
            ],
        ),
    ]
